% Do `erl -make` to build project
% Start shell via `erl -pa ebin/`
% and do `make:all([load]).` to recompile.
{'src/*', [debug_info,
           {i, "include"},
           {outdir, "ebin"}]}.
{'test/*', [debug_info,
           {i, "include"},
           {outdir, "ebin"}]}.
